### ISSUE TITLE
How to get the  private Key of  address ?

### ISSUE THREAD

**Issue by jaslin-W** [SiaFoundation/siad#138]
Hello teams.
I want to get the private Key of address generate by sia-UI. I know it can export the primary private key. But how to get all private keys?
Thank you.

**Comment by lukechampine** [comment]
To do this, you will need a Go program that converts your seed phrase to bytes, concatenates it with a seed index, and hashes the result.
Can I ask why you want to do this?

**Comment by jaslin-W** [comment]
we are exchange. we want to manage the siacoin's deposit/withdrawal with ourselves code. so we want to migrate the address/privateKey from sia-ui to ourselves program.
Thanks. I find the related code about generating address
