### ISSUE TITLE
Sia Host Manager + Ubuntu LTS 22.04 directory problem

### ISSUE THREAD

**Issue by j03020** [SiaFoundation/siad#149]
After updating to the new Ubuntu LTS Sia Host Manager gives me an error message that it can't access the file directories. I have asked the people at SHM and they said it's a problem with siad. I did not change any permissions to the directories so I'm wondering if someone else has encountered this problem or might have a tip on how to resolve the problem? I'm still finishing most of my contracts though.

**Comment by n8maninger** [comment]
Did you check the host's `contractmanager.log`? It should be here: `~/.config/Sia-UI/sia/host/contractmanager/contractmanager.log`.

Discord is better for setup support: https://discord.gg/sia
