### ISSUE TITLE
/host/bandiwdth API results in 491 Module disabled

### ISSUE THREAD

**Issue by ocha** [SiaFoundation/siad#31]
I am trying to query [/host/bandiwdth API](https://sia.tech/docs/#host-bandwidth-get), but I am getting following response: `{"message":"491 Module disabled - Refer to API.md"}`. I have all modules enabled besides `Miner` (`/usr/local/bin/siad -M gctwhar`). Is API documentation wrong or am I missing something? I am using latest build from master (`Git Revision ✗-6234126c7`).

**Comment by n8maninger** [comment]
The command from the documentation works for me on latest master: `curl -A "Sia-Agent" "localhost:9980/host/bandwidth"`. Did you wait for the `API is now available, ...` message before querying the endpoint?

**Comment by ocha** [comment]
You are right. It took over 5 minutes to fully boot up. After that it started working. Thanks!
