### ISSUE TITLE
[Feature Request] Switch to disable uPnP discovery

### ISSUE THREAD

**Issue by NickJH** [SiaFoundation/siad#42]
Please can a switch be added to disable uPnP discovery and port mapping?

My use case is that I have a /29 block of IP addresses (x.y.z.88-95). My router base address is x.y.z.90 and I have allocated Sia x.y.z.91 using a 1-to-1 NAT function. In the router, uPnP mappings take precedence over 1-to-1 NAT so siad discovers its external IP as x.y.z.90 and not x.y.z.91. Turning off uPnP in the router is a global setting. I have had to resort to blocking incoming TCP:1900 (uPnP discovery) from the Sia LAN IP to disable the uPnP discovery from Sia, but it would be much better if siad had a switch to stop it.

**Comment by lukechampine** [comment]
Seems reasonable to me. The current behavior is to fallback to querying `myexternalip.com`; is that the behavior you want? I'm wondering if we should add a `--hostname=1.2.3.4` flag instead of a `--disable-upnp` flag. 🤔

**Comment by NickJH** [comment]
The current fallback for me works correctly when I block the server from accessing the router's uPnP. From the gateway.log on startup:
```
2021/09/26 08:05:36.099168 log.go:29: STARTUP: Commit hash 985b664c9
2021/09/26 08:05:36.099194 gateway.go:404: INFO: gateway created, started logging
2021/09/26 08:06:19.890910 ip.go:97: ip successfully discovered using peers: 62.30.63.91
2021/09/26 08:06:19.891071 upnp.go:135: INFO: our address is 62.30.63.91:9981
2021/09/26 08:06:20.453897 upnp.go:234: INFO: successfully forwarded port 9981
2021/09/26 08:06:22.879531 ip.go:97: ip successfully discovered using peers: 62.30.63.91
2021/09/26 08:36:40.937262 ip.go:97: ip successfully discovered using peers: 62.30.63.91
2021/09/26 09:07:18.797680 ip.go:97: ip successfully discovered using peers: 62.30.63.91
```
A `--hostname=` switch may have its drawbacks if you are behind a router with a dynamic IP.

**Comment by lukechampine** [comment]
True. Let's go with a `--upnp` flag, true by default.
